### ISSUE TITLE
I'm working on launchreadyapps very similar, wondering if you'd be interested in partner

### ISSUE THREAD

**Issue by cameronking4** [alifarooq9/rapidlaunch#15]
Happy to contribute

**Comment by alifarooq9** [comment]
I am currently working on roadmap, once  I am done you can contribute if you like.

Just telling I will create page where I will redirect the audience to my MVP as a service.

**Comment by Sudarsh1010** [comment]
waiting for roadmap, happy to contribute

**Comment by alifarooq9** [comment]
> waiting for roadmap, happy to contribute

Roadmap has been added, Please check and if you can give suggestions it would be very appreciated.

Thank you for supporting Rapidlaunch
