### ISSUE TITLE
improvements on accessibility

### ISSUE THREAD

**Issue by Milind-Jamnekar** [alifarooq9/rapidlaunch#36]
First of all, great project 👏 @alifarooq9, I liked it. so while digging around I saw some part could have improvement in accessibility from [lighthouse](https://pagespeed.web.dev/analysis/https-www-rapidlaunch-xyz/4e9xsadb0s?form_factor=desktop), like tabs 
<img width="769" alt="Screenshot 2024-05-22 at 5 50 40 PM" src="https://github.com/alifarooq9/rapidlaunch/assets/58872755/4b7a9017-92fc-42c5-ba67-7190260ead0e">
 and some header buttons 
<img width="185" alt="Screenshot 2024-05-22 at 5 53 36 PM" src="https://github.com/alifarooq9/rapidlaunch/assets/58872755/090197e6-4c22-49e7-8405-7dc0d0177464"> either you could do it or I could do it in instant

**Comment by alifarooq9** [comment]
I am currently working this. making the www from the scratch.

**Comment by Milind-Jamnekar** [comment]
> I am currently working this. making the www from the scratch.
that's great. ohh and those same improvements need to be on starter kits demo site as well
<img width="362" alt="Screenshot 2024-05-22 at 6 14 05 PM" src="https://github.com/alifarooq9/rapidlaunch/assets/58872755/bdf9a161-b320-4b4b-9e8b-08b2a78baaf5">

**Comment by Milind-Jamnekar** [comment]
Ok I'm on it 🫡
